<?php

namespace Ceb\PhotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TravauxfiniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravauxfiniRepository extends EntityRepository
{
}