ceb_contact_contact:
    pattern:  /Nous-contacter
    defaults: { _controller: CebAutreBundle:Default:contact }

ceb_partenaire_homepage:
    pattern:   /Nos-partenaires
    defaults: { _controller: CebAutreBundle:Default:partenaire }

ceb_present_homepage:
    pattern:   /Presentation-entreprise
    defaults: { _controller: CebAutreBundle:Default:presentation }