ceb_photo_homepage:
    pattern:  /home
    defaults: { _controller: CebPhotoBundle:Default:index }

ceb_photo_cuisine:
    pattern:  /photocuisine
    defaults: { _controller: CebPhotoBundle:Default:cuisine }

ceb_photo_bain:
    pattern:  /photobain
    defaults: { _controller: CebPhotoBundle:Default:bain }

ceb_photo_finition:
    pattern:  /photofinition
    defaults: { _controller: CebPhotoBundle:Default:finition }

uploadbain:
    pattern:  /admin/upload/bain
    defaults: { _controller: CebPhotoBundle:Default:uploadBain }

succes:
    pattern:  /admin/succes
    defaults: { _controller: CebPhotoBundle:Default:succes }

succes:
    pattern:  /admin/erreur
    defaults: { _controller: CebPhotoBundle:Default:erreur }

deleteBain:
    pattern:  /admin/delete/bain
    defaults: { _controller: CebPhotoBundle:Default:deleteBain }

destroyBain:
    pattern:  /admin/delete/bain/{id}
    defaults: { _controller: CebPhotoBundle:Default:DestroyBain }