ceb_photo_homepage:
    pattern:  /home
    defaults: { _controller: CebPhotoBundle:Default:index }

ceb_photo_cuisine:
    pattern:  /photocuisine
    defaults: { _controller: CebPhotoBundle:Default:cuisine }

ceb_photo_bain:
    pattern:  /photobain
    defaults: { _controller: CebPhotoBundle:Default:bain }

ceb_photo_finition:
    pattern:  /photofinition
    defaults: { _controller: CebPhotoBundle:Default:finition }

upload:
    pattern:  /upload
    defaults: { _controller: CebPhotoBundle:Default:upload }

succes:
    pattern:  /succes
    defaults: { _controller: CebPhotoBundle:Default:succes }

succes:
    pattern:  /erreur
    defaults: { _controller: CebPhotoBundle:Default:erreur }

deleteBain:
    pattern:  /delete/bain
    defaults: { _controller: CebPhotoBundle:Default:deleteBain }

destroyBain:
    pattern:  /delete/bain/{id}
    defaults: { _controller: CebPhotoBundle:Default:DestroyBain }